# Generated by Django 3.1.2 on 2021-04-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_auto_20210409_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='discord',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='event_bio',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
    ]
