# Generated by Django 3.2 on 2021-04-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_auto_20210411_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wanna_Add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_title', models.CharField(blank=True, max_length=300, null=True)),
                ('activity_club', models.CharField(blank=True, max_length=300, null=True)),
                ('activity_date', models.DateField(blank=True, null=True)),
                ('activity_time', models.TimeField(blank=True, null=True)),
                ('activity_details', models.CharField(blank=True, max_length=600, null=True)),
            ],
        ),
    ]
