# Generated by Django 3.2 on 2021-06-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_wanna_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='club_logo',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='feedback',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='register',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
    ]
