# Generated by Django 3.2 on 2021-06-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_auto_20210610_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='linkedin',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='recording',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
    ]
